export const LOGIN_USER = "LOGIN_USER";
export const CHECK_PROTECTED = "CHECK_PROTECTED";

export const SET_AUTH_TOKEN = "SET_AUTH_TOKEN";
export const REQUEST_ERROR = "REQUEST_ERROR";

export const SIGN_UP_USER = "SIGN_UP_USER";

export const CLEAR_REGISTRATION_ERROR = "CLEAR_REGISTRATION_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCTS = "GET_PRODUCTS";

export const SET_LOADING = "SET_LOADING";
